CONFIG:
  TEMPLATE_PATH: 
    - BIA_TJC_AUTOMATION/templates
    - BIA_TJC_AUTOMATION/templates/FULLAPPLY
  OUTPUT_DIR: BIA_TJC_AUTOMATION/output
  CONFIG_DIR: BIA_TJC_AUTOMATION/config
  TMP_DIR:  BIA_TJC_AUTOMATION/tmp
  WRITE_CONFIG_TO_TMP: YES
  FILE_SPLITTER_RE:  "/* FILE_SLIT|<[\\w\\-.\\s]+> */"