JOB: IDW1001
PROJECT:
  COMPANY: The Big Company
  DATE: '2021-09-21'
  PURPOSE: The Big Job
  TEAM: BOBS TEAM
SYSTEM: IDW
TARGET:
  COLUMNS:
    LOC_ID:
      DATATYPE: VARCHAR(30)
      NULLABLE: N
      PINDEX: N
      TKEY: N
    LOC_NAME:
      DATATYPE: VARCHAR(100)
      NULLABLE: Y
      PINDEX: N
      TKEY: N
    LOC_SBTYPE_CD:
      DATATYPE: VARCHAR(30)
      NULLABLE: N
      PINDEX: Y
      TKEY: Y
    LOC_WID:
      DATATYPE: BIGINT
      NULLABLE: N
      PINDEX: Y
      TKEY: Y
  DATABASE: IDW
  FILE_ID_IND: Y
  SRC_ID_IND: Y
  TABLE: LOC
TARGET_STEP_NO: '400'
TRANS_STEP_NO: '200'
VALID_COLLECT_STATS: Y
VALID_LOGICAL_DEL: Y
VALID_STEP_NO: '300'
