PROJECT:
  COMPANY: Primark
  DATE: '2021-11-23'
  PURPOSE: OLR Data Mover Setup
  TEAM: TERADATA , GCC
  SYSTEM_DESC: Online Reporting
  SYSTEM: OLR
CHANGE_CONTROL:
  RFC: RFC000723
DATAMOVER:
  JOBS:
    DMV1432:
      DATABASE: DWP01T_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMV
      CRON_SCHEDULE: "11 20 * * *"
    DMV1433:
      DATABASE: DWP01V_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMV
      CRON_SCHEDULE: "11 20 * * *"
    DMV1434:
      DATABASE: DWP01A_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMV
      CRON_SCHEDULE: "11 20 * * *"
    DMV1435:
      DATABASE: DWP01C_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMV
      CRON_SCHEDULE: "11 20 * * *"
    DMV1436:
      DATABASE: DWP01T_TMP_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMV
      CRON_SCHEDULE: "11 20 * * *"
    DMB1432:
      DATABASE: DWP01T_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMB
      CRON_SCHEDULE: "11 20 * * *"
    DMB1433:
      DATABASE: DWP01V_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMB
      CRON_SCHEDULE: "11 20 * * *"
    DMB1434:
      DATABASE: DWP01A_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMB
    DMB1435:
      DATABASE: DWP01C_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMB
      CRON_SCHEDULE: "11 20 * * *"
    DMB1436:
      DATABASE: DWP01T_TMP_ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMB
      CRON_SCHEDULE: "11 20 * * *"
    DMM1021:
      DATABASE: ACC_OLR
      DEPENDENCY: OLR1001
      TYPE: DMM
      CRON_SCHEDULE: "00 20 * * *"
    DMM9021:
      DATABASE: ACC_OLR
      DEPENDENCY: DMM1021
      TYPE: DMM
      CRON_SCHEDULE: "30 20 * * *"      
